### PR TITLE
Removed Broken link.

### PR DESCRIPTION
**Pull request by yogesh-desai**
Hello @digitalcraftsman,

I have removed the broken link. Please do accept this **pull request**.

Thank you,
Yogesh Desai

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Hello Yogesh,

thanks for your pull request. But why did you add Travis CI and changed the URL for the `go get` command to your fork?

**Comment by yogesh-desai** [comment]
Hello @digitalcraftsman,

Having "Travis CI " is good. It checks automatically about the builds as we commit the code every time. Check more info [here](https://docs.travis-ci.com/user/getting-started/).
Apologies regarding "go get". Now, I have updated it with your repo.

**Comment by digitalcraftsman** [comment]
> Having "Travis CI " is good. It checks automatically about the builds as we commit the code every time. Check more info here.

I know about continuous integration and that it can be useful tool. In this case it very likely that the code in this repository will not change in the future nor do I have plans do change it. The code is just there for people who might find it useful. So I hope you don't see this as an offence.

**Comment by yogesh-desai** [comment]
@digitalcraftsman,
Yes, sure; no problem at all. What to do now? I think keeping it will not affect anything. But you can suggest how to proceed. Let me know if you feel to remove it; I will make the change so you can merge the pull request.

**Comment by digitalcraftsman** [comment]
Please remove the `.travis.yml` file and status badge. Then I'll squash your commits and merge this pull request :)

**Comment by yogesh-desai** [comment]
@digitalcraftsman,

I have removed ```.travis.yml``` Please proceed with the merge. 
Thank you. :)

**Comment by digitalcraftsman** [comment]
Here we go - thanks again for your patience @yogesh-desai

**Pull request merged**
